apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
  namespace: prod
spec:
  ingressClassName: nginx
  rules:
    - host: songlnwza.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 80