apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          envFrom:
            - secretRef:
                name: app-secret
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: prod
spec:
  ports:
    - port: 5050
      targetPort: 80
  selector:
    app: pgadmin
