name: Deploy to AKS

on:
  push:
    branches: [main]

env:
  IMAGE: songlnwzacr.azurecr.io/app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Login ACR
        run: az acr login --name songlnwzacr


      - name: Build & Push
        run: |
          docker build -t $IMAGE:${{ github.sha }} .
          docker push $IMAGE:${{ github.sha }}


      - name: Set Kubeconfig
        run: |
          az aks get-credentials --resource-group my-rg --name songlnwzak8s --overwrite-existing

      - name: Install Helm
        uses: azure/setup-helm@v3


      - name: Install cert-manager
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo update

          helm upgrade --install cert-manager jetstack/cert-manager \
            --namespace cert-manager \
            --create-namespace \
            --set crds.enabled=true

          echo "Waiting for cert-manager..."
          kubectl rollout status deployment/cert-manager -n cert-manager --timeout=180s


      - name: Deploy
        run: |
          # Ensure prod namespace exists
          kubectl create namespace prod --dry-run=client -o yaml | kubectl apply -f -

          # Create secret from GitHub Actions secret
          echo "${{ secrets.ENV_FILE }}" > .env
          kubectl create secret generic app-secret \
            --from-env-file=.env \
            --namespace prod \
            --dry-run=client -o yaml | kubectl apply -f -
          rm .env

          # Apply manifests (รวม ClusterIssuer ด้วย)
          kubectl apply -f infra/k8s/

          # Update image
          kubectl set image deployment/app app=$IMAGE:${{ github.sha }} -n prod

          # Wait rollout
          kubectl rollout status deployment/app -n prod --timeout=180s