name: Deploy to AKS

on:
  push:
    branches: [main]

env:
  IMAGE: songlnwzacr.azurecr.io/app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login ACR
        run: az acr login --name songlnwzacr

      - name: Build & Push
        run: |
          docker build -t $IMAGE:${{ github.sha }} .
          docker push $IMAGE:${{ github.sha }}

      - name: Set Kubeconfig
        run: |
          az aks get-credentials --resource-group my-rg --name songlnwzak8s

      - name: Deploy
        run: |
          # Create secret from GitHub Actions secret
          echo "${{ secrets.ENV_FILE }}" > .env
          kubectl create secret generic app-secret --from-env-file=.env --namespace prod --dry-run=client -o yaml | kubectl apply -f -
          rm .env
          
          # Deploy Kubernetes manifests
          kubectl apply -f infra/k8s/
          kubectl set image deployment/app app=$IMAGE:${{ github.sha }} -n prod